name: Android Build with Buildozer
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Clean buildozer.spec
        run: |
          # Remove duplicate [app] sections while preserving all other content
          awk '/^\[app\]/ && !found {found=1; print; next} /^\[app\]/ && found {next} {print}' buildozer.spec > buildozer.spec.tmp
          mv buildozer.spec.tmp buildozer.spec
          
          # Remove duplicate keys within sections
          awk -F= '!seen[$1]++' buildozer.spec > buildozer.spec.tmp
          mv buildozer.spec.tmp buildozer.spec

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.18"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
              git zip unzip openjdk-17-jdk \
              python3-pip autoconf libtool \
              pkg-config zlib1g-dev libncurses6 \
              libtinfo6 libffi-dev libssl-dev

      - name: Install Buildozer
        run: |
          python -m pip install --upgrade pip
          pip install buildozer python-for-android

      - name: Set up Android SDK
        run: |
          mkdir -p ~/.android
          touch ~/.android/repositories.cfg

          wget https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip -O cmdline-tools.zip
          unzip cmdline-tools.zip -d ~/.android/cmdline-tools
          mv ~/.android/cmdline-tools/cmdline-tools ~/.android/cmdline-tools/latest

          echo "ANDROID_SDK_ROOT=$HOME/.android" >> $GITHUB_ENV
          echo "PATH=$HOME/.android/cmdline-tools/latest/bin:$PATH" >> $GITHUB_ENV

          yes | ~/.android/cmdline-tools/latest/bin/sdkmanager --licenses
          ~/.android/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      - name: Install Android NDK
        run: |
          ~/.android/cmdline-tools/latest/bin/sdkmanager "ndk;25.2.9519653"
          echo "ANDROID_NDK_HOME=$HOME/.android/ndk/25.2.9519653" >> $GITHUB_ENV

      - name: Update buildozer.spec paths
        run: |
          # Remove existing path entries if they exist
          sed -i '/^android.ndk_path/d' buildozer.spec
          sed -i '/^android.sdk_path/d' buildozer.spec
          
          # Add them in the correct [app] section
          awk '1; /^\[app\]/ && !added {print "android.ndk_path = $ANDROID_NDK_HOME"; print "android.sdk_path = $ANDROID_SDK_ROOT"; added=1}' buildozer.spec > buildozer.spec.tmp
          mv buildozer.spec.tmp buildozer.spec

      - name: Build APK
        run: |
          buildozer android clean
          buildozer android debug
