name: Android Build with Buildozer
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.18"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
              git zip unzip openjdk-17-jdk \
              python3-pip autoconf libtool \
              pkg-config zlib1g-dev libncurses6 \
              libtinfo6 libffi-dev libssl-dev

      - name: Install Buildozer and python-for-android
        run: |
          python -m pip install --upgrade pip
          pip install buildozer python-for-android

      - name: Initialize Buildozer environment
        run: |
          # Create required directories
          mkdir -p .buildozer/android/platform/python-for-android
          
          # Initialize if no spec file exists
          if [ ! -f buildozer.spec ]; then
            buildozer init
          fi

      - name: Install Android SDK and NDK
        run: |
          mkdir -p ~/.android
          touch ~/.android/repositories.cfg

          # Install Android Command Line Tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip -O cmdline-tools.zip
          unzip cmdline-tools.zip -d ~/.android/cmdline-tools
          mv ~/.android/cmdline-tools/cmdline-tools ~/.android/cmdline-tools/latest

          # Set environment variables
          echo "ANDROID_SDK_ROOT=$HOME/.android" >> $GITHUB_ENV
          echo "PATH=$HOME/.android/cmdline-tools/latest/bin:$HOME/.android/platform-tools:$PATH" >> $GITHUB_ENV

          # Accept licenses and install components
          yes | ~/.android/cmdline-tools/latest/bin/sdkmanager --licenses
          ~/.android/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"

          # Install NDK
          ~/.android/cmdline-tools/latest/bin/sdkmanager "ndk;25.2.9519653"
          echo "ANDROID_NDK_HOME=$HOME/.android/ndk/25.2.9519653" >> $GITHUB_ENV

      - name: Configure buildozer.spec
        run: |
          echo "[app]" >> buildozer.spec
          echo "android.ndk_path = $ANDROID_NDK_HOME" >> buildozer.spec
          echo "android.sdk_path = $ANDROID_SDK_ROOT" >> buildozer.spec
          echo "p4a.branch = master" >> buildozer.spec

      - name: Run Buildozer
        run: |
          buildozer android clean
          buildozer android debug
