name: Android Build with Buildozer
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update package lists
        run: sudo apt-get update -y

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.18"

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install essential packages
        run: |
          sudo apt-get install -y \
              git zip unzip \
              libncurses6 libtinfo6 \
              python3-pip python3-dev \
              autoconf automake libtool \
              pkg-config zlib1g-dev \
              libffi-dev libssl-dev

      - name: Install Buildozer and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install buildozer cython virtualenv
          pip install python-for-android

      - name: Initialize Buildozer
        run: |
          buildozer init
          mkdir -p .buildozer/android/platform/python-for-android

      - name: Install Android SDK and NDK
        run: |
          mkdir -p ~/.android
          touch ~/.android/repositories.cfg

          # Download command line tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip -O cmdline-tools.zip
          unzip cmdline-tools.zip -d ~/.android/cmdline-tools
          mv ~/.android/cmdline-tools/cmdline-tools ~/.android/cmdline-tools/latest

          # Set environment variables
          echo "ANDROID_SDK_ROOT=$HOME/.android" >> $GITHUB_ENV
          echo "$HOME/.android/cmdline-tools/latest/bin:$HOME/.android/platform-tools" >> $GITHUB_PATH

          # Accept licenses and install components
          yes | ~/.android/cmdline-tools/latest/bin/sdkmanager --licenses
          ~/.android/cmdline-tools/latest/bin/sdkmanager \
              "platform-tools" \
              "platforms;android-34" \
              "build-tools;34.0.0"

          # Install NDK
          buildozer android ndk install

      - name: Build APK
        run: |
          buildozer android clean
          buildozer android debug
