name: Android Build with Buildozer
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update package lists
        run: sudo apt-get update -y

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.18"

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install essential packages
        run: |
          sudo apt-get install -y \
              git zip unzip \
              libncurses6 libtinfo6 \
              python3-pip python3-dev \
              autoconf automake libtool \
              pkg-config zlib1g-dev \
              libffi-dev libssl-dev

      - name: Install Buildozer and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install buildozer cython virtualenv
          pip install python-for-android

      - name: Clean existing buildozer.spec duplicates
        run: |
          # Backup original spec file
          cp buildozer.spec buildozer.spec.bak
          # Remove duplicate [app] sections
          awk '/^\[app\]/ && !found {found=1; print; next} /^\[app\]/ && found {next} {print}' buildozer.spec.bak > buildozer.spec

      - name: Install Android SDK
        run: |
          mkdir -p ~/.android
          touch ~/.android/repositories.cfg

          wget https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip -O cmdline-tools.zip
          unzip cmdline-tools.zip -d ~/.android/cmdline-tools
          mv ~/.android/cmdline-tools/cmdline-tools ~/.android/cmdline-tools/latest

          echo "ANDROID_SDK_ROOT=$HOME/.android" >> $GITHUB_ENV
          echo "$HOME/.android/cmdline-tools/latest/bin:$HOME/.android/platform-tools" >> $GITHUB_PATH

          yes | ~/.android/cmdline-tools/latest/bin/sdkmanager --licenses
          ~/.android/cmdline-tools/latest/bin/sdkmanager \
              "platform-tools" \
              "platforms;android-34" \
              "build-tools;34.0.0"

      - name: Install Android NDK
        run: |
          NDK_VERSION="25b"
          wget https://dl.google.com/android/repository/android-ndk-r${NDK_VERSION}-linux.zip
          unzip android-ndk-r${NDK_VERSION}-linux.zip -d ~/
          mv ~/android-ndk-r${NDK_VERSION} ~/.android/android-ndk
          echo "ANDROID_NDK_HOME=$HOME/.android/android-ndk" >> $GITHUB_ENV

          # Update buildozer.spec with correct paths
          sed -i "/^android.ndk_path/d" buildozer.spec
          sed -i "/^android.sdk_path/d" buildozer.spec
          echo "android.ndk_path = $HOME/.android/android-ndk" >> buildozer.spec
          echo "android.sdk_path = $HOME/.android" >> buildozer.spec

      - name: Build APK
        run: |
          buildozer android clean
          buildozer android debug
