name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.1

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y zip unzip openjdk-17-jdk python3-pip git

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install cython buildozer

      - name: Build APK
        run: |
          buildozer android debug


      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.1  # ✅ Fixed version

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y zip unzip openjdk-17-jdk python3-pip
          pip install --upgrade pip
          pip install buildozer

      - name: Build APK with Buildozer
        run: |
          buildozer android debug
