name: Android Build with Buildozer
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Clean buildozer.spec
        run: |
          awk '/^\[app\]/ && !found {found=1; print; next} /^\[app\]/ && found {next} {print}' buildozer.spec > buildozer.spec.tmp
          mv buildozer.spec.tmp buildozer.spec
          awk -F= '!seen[$1]++' buildozer.spec > buildozer.spec.tmp
          mv buildozer.spec.tmp buildozer.spec

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.12"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
              git zip unzip openjdk-17-jdk \
              python3-pip autoconf libtool \
              pkg-config zlib1g-dev libncurses6 \
              libtinfo6 libffi-dev libssl-dev \
              build-essential python3-dev

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cython==0.29.33  # Explicit version for compatibility
          pip install buildozer
          pip install --force-reinstall python-for-android

      - name: Create required directories
        run: |
          mkdir -p .buildozer/android/platform/python-for-android
          mkdir -p .buildozer/android/platform/build

      - name: Set up Android SDK
        run: |
          mkdir -p ~/.android
          touch ~/.android/repositories.cfg

          wget https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip -O cmdline-tools.zip
          unzip cmdline-tools.zip -d ~/.android/cmdline-tools
          mv ~/.android/cmdline-tools/cmdline-tools ~/.android/cmdline-tools/latest

          echo "ANDROID_SDK_ROOT=$HOME/.android" >> $GITHUB_ENV
          echo "PATH=$HOME/.android/cmdline-tools/latest/bin:$HOME/.android/platform-tools:$PATH" >> $GITHUB_ENV

          yes | ~/.android/cmdline-tools/latest/bin/sdkmanager --licenses
          ~/.android/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      - name: Install Android NDK
        run: |
          ~/.android/cmdline-tools/latest/bin/sdkmanager "ndk;25.2.9519653"
          echo "ANDROID_NDK_HOME=$HOME/.android/ndk/25.2.9519653" >> $GITHUB_ENV

      - name: Update buildozer.spec
        run: |
          sed -i '/^android.ndk_path/d' buildozer.spec
          sed -i '/^android.sdk_path/d' buildozer.spec
          sed -i '/^p4a.branch/d' buildozer.spec
          sed -i '/^requirements/d' buildozer.spec
          
          awk '1; /^\[app\]/ && !added {print "android.ndk_path = $ANDROID_NDK_HOME"; print "android.sdk_path = $ANDROID_SDK_ROOT"; print "p4a.branch = develop"; print "requirements = python3,kivy,cython==0.29.33"; added=1}' buildozer.spec > buildozer.spec.tmp
          mv buildozer.spec.tmp buildozer.spec

      - name: Verify environment
        run: |
          echo "=== Installed Packages ==="
          pip list
          echo "=== Cython Version ==="
          cython --version
          echo "=== Buildozer Version ==="
          buildozer --version
          echo "=== Android Tools ==="
          ls $ANDROID_SDK_ROOT/build-tools

      - name: Build APK
        run: |
          buildozer android clean
          buildozer android debug
